"""Application settings — profile loading, branding, and per-agent configuration.

Configuration comes from three layers, each overriding the previous:

  1. The checked-in profile (``profiles/<APP_PROFILE>/profile.json`` +
     ``profiles/<APP_PROFILE>/prompts/*.txt``) — branding and per-agent
     defaults (name, role, deployment, endpoint, temperature, prompt).
  2. Global environment variables (``AZURE_OPENAI_ENDPOINT``, etc.) —
     unchanged from prior releases for backward compatibility.
  3. Per-agent environment variables (``AGENT_<KEY>_<FIELD>``) — optional,
     surgical overrides for a single agent without forking a whole profile.

``APP_PROFILE`` defaults to "power" — a generic power-utility reference
deployment (see profiles/power/ and docs/MODEL_CONFIGURATION.md). Setting
``APP_PROFILE`` to another checked-in profile (e.g. "generic", the legacy
"oge" profile, or a customer's own profile copied from "generic")
re-brands the app and re-routes/renames agents without any code changes.

Any malformed profile or invalid override raises ``ProfileError`` (a
``ValueError`` subclass) at startup — this module never silently falls
back to a guessed value for broken configuration.
"""

import os
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from dotenv import load_dotenv

from app.profiles import (
    AGENT_KEYS,
    DEFAULT_API_VERSION,
    DEFAULT_PROFILE,
    REPO_ROOT,
    ProfileError,
    load_profile_document,
    load_prompt,
    resolve_profile_dir,
)

# Load a local .env (generated by scripts/configure.py, or hand-written
# from .env.example) before anything below reads os.environ. Never
# overrides variables already set in the real environment (e.g. Azure App
# Service settings), and is a silent no-op if .env doesn't exist — both
# are the correct, expected defaults for local dev vs. production.
load_dotenv(dotenv_path=REPO_ROOT / ".env")

__all__ = [
    "AgentConfig",
    "BrandMetadata",
    "Settings",
    "ProfileError",
    "settings",
]

_TRUE_VALUES = {"1", "true", "yes", "on"}
_FALSE_VALUES = {"0", "false", "no", "off"}


@dataclass
class AgentConfig:
    key: str
    name: str
    role: str
    deployment: str
    system_prompt: str
    temperature: float = 1.0
    # Some deployments (e.g. o-series/GPT-5-style reasoning models) only
    # accept the default temperature (1.0) and error if any other value is
    # sent. This flag — not a hardcoded deployment-name list — decides
    # whether `temperature` is actually sent on each call. See
    # app/agents/runner.py::call_agent.
    supports_temperature: bool = False
    endpoint: str = ""  # resolved absolute endpoint URL ("" = use default endpoint)
    api_version: str = DEFAULT_API_VERSION
    # Enforceable token/response/personality controls — see
    # docs/MODEL_CONFIGURATION.md for the full convention and rationale.
    # 0 (the default) means "provider default" — the max_completion_tokens
    # argument is omitted from the chat.completions call entirely.
    max_completion_tokens: int = 0
    # 0 (the default) means "no truncation" of context_data. Character
    # counts are an approximation of token counts (roughly 3-4 characters
    # per token for English text), not exact token accounting.
    max_context_chars: int = 0
    # Appended as its own instruction message on every call (see
    # app/agents/runner.py::call_agent). Empty string = no extra
    # instruction beyond the profile's system_prompt.
    response_instruction: str = ""
    # Caller-maintained cost-per-million-token estimates for telemetry
    # only — not billing truth. 0.0 means "don't estimate a cost".
    input_cost_per_million: float = 0.0
    output_cost_per_million: float = 0.0


@dataclass
class BrandMetadata:
    app_name: str
    app_title: str
    tagline_line1: str
    tagline_line2: str
    executive_subtitle: str
    logo_path: str
    logo_alt: str
    customer: str = ""
    industry: str = ""


def _agent_env_prefix(agent_key: str) -> str:
    """e.g. 'cost_sentinel' -> 'AGENT_COST_SENTINEL'."""
    return f"AGENT_{agent_key.upper()}"


def _parse_bool(value: str, context: str) -> bool:
    normalized = value.strip().lower()
    if normalized in _TRUE_VALUES:
        return True
    if normalized in _FALSE_VALUES:
        return False
    raise ProfileError(f"{context}: expected a boolean (true/false/1/0/yes/no), got {value!r}.")


def _parse_nonneg_int(value: str, context: str) -> int:
    """Strictly parse a non-negative integer env var value (no floats, no signs beyond a bare number)."""
    try:
        parsed = int(value.strip())
    except ValueError as exc:
        raise ProfileError(f"{context}: expected a non-negative integer, got {value!r}.") from exc
    if parsed < 0:
        raise ProfileError(f"{context}: expected a non-negative integer, got {parsed}.")
    return parsed


def _parse_nonneg_float(value: str, context: str) -> float:
    try:
        parsed = float(value.strip())
    except ValueError as exc:
        raise ProfileError(f"{context}: expected a non-negative number, got {value!r}.") from exc
    if parsed < 0:
        raise ProfileError(f"{context}: expected a non-negative number, got {parsed}.")
    return parsed


def _build_endpoint_registry() -> dict:
    """Build a name -> URL map from AZURE_OPENAI_ENDPOINT* environment variables.

    "AZURE_OPENAI_ENDPOINT" itself registers as "primary". Any
    "AZURE_OPENAI_ENDPOINT_<NAME>" (e.g. "..._SECONDARY", "..._TERTIARY")
    registers as "<name>" (lowercased). This lets a profile or an
    AGENT_<KEY>_ENDPOINT override reference an endpoint by name instead of
    repeating the full URL, without capping the number of endpoints.
    """
    registry: dict = {}
    primary = os.environ.get("AZURE_OPENAI_ENDPOINT", "").strip()
    if primary:
        registry["primary"] = primary
    prefix = "AZURE_OPENAI_ENDPOINT_"
    for env_name, raw_value in os.environ.items():
        if env_name == "AZURE_OPENAI_ENDPOINT" or not env_name.startswith(prefix):
            continue
        value = raw_value.strip()
        if not value:
            continue
        registry[env_name[len(prefix):].lower()] = value
    return registry


# "secondary" has always been a first-class, optional endpoint slot (see the
# historical AZURE_OPENAI_ENDPOINT_SECONDARY / openai_endpoint_eastus2
# fields). Referencing it when it hasn't been configured yet is a normal,
# valid state (falls back to the primary endpoint) — not a misconfiguration.
# Any *other* named reference that isn't registered is treated as a typo/
# genuine error, since there's no legacy behavior to preserve for it.
_OPTIONAL_ENDPOINT_REFS = {"secondary"}


def _resolve_endpoint(ref: str, registry: dict, context: str) -> str:
    """Resolve an endpoint_ref (profile/env value) to an absolute URL or "".

    ref may be: "" or "primary" (use the default endpoint), a literal
    https:// URL, or a named reference registered via
    AZURE_OPENAI_ENDPOINT_<NAME>.
    """
    ref = (ref or "").strip()
    if not ref or ref.lower() == "primary":
        return ""
    lowered = ref.lower()
    if lowered.startswith("http://") or lowered.startswith("https://"):
        return ref
    resolved = registry.get(lowered)
    if resolved is not None:
        return resolved
    if lowered in _OPTIONAL_ENDPOINT_REFS:
        return ""
    raise ProfileError(
        f"{context}: unknown endpoint reference {ref!r}. Define it with an "
        f"AZURE_OPENAI_ENDPOINT_{ref.upper()} environment variable, or use a literal "
        "https:// URL."
    )


@dataclass
class Settings:
    # Which checked-in profile (profiles/<id>/) to load. Defaults to "oge",
    # which reproduces the app's original hardcoded branding/agents exactly.
    profile_id: str = os.environ.get("APP_PROFILE", DEFAULT_PROFILE)

    # Azure OpenAI — primary/default endpoint and deployment.
    openai_endpoint: str = os.environ.get("AZURE_OPENAI_ENDPOINT", "")
    openai_deployment: str = os.environ.get("AZURE_OPENAI_DEPLOYMENT", "foundry-gpt")
    openai_api_version: str = os.environ.get("AZURE_OPENAI_API_VERSION", DEFAULT_API_VERSION)
    azure_client_id: str = os.environ.get("AZURE_CLIENT_ID", "")

    # Azure OpenAI — secondary endpoint (for models on a different account).
    # Kept as an explicit field for backward compatibility; equivalent to
    # (and kept in sync with) the "secondary" entry in the endpoint registry.
    openai_endpoint_eastus2: str = os.environ.get("AZURE_OPENAI_ENDPOINT_SECONDARY", "")

    # Key Vault
    key_vault_uri: str = os.environ.get("KEY_VAULT_URI", "")

    # Monitoring
    log_analytics_workspace_id: str = os.environ.get("LOG_ANALYTICS_WORKSPACE_ID", "")

    # Subscription scope (single sub for PoC)
    subscription_id: str = os.environ.get("AZURE_SUBSCRIPTION_ID", "")

    # Populated in __post_init__ from the profile + env var overrides.
    agents: dict = field(default_factory=dict)
    brand: Optional[BrandMetadata] = None

    def __post_init__(self):
        profile_dir = resolve_profile_dir(self.profile_id)
        document = load_profile_document(profile_dir, self.profile_id)

        brand_doc = document["brand"]
        self.brand = BrandMetadata(
            app_name=brand_doc["app_name"],
            app_title=brand_doc["app_title"],
            tagline_line1=brand_doc["tagline_line1"],
            tagline_line2=brand_doc["tagline_line2"],
            executive_subtitle=brand_doc["executive_subtitle"],
            logo_path=brand_doc["logo_path"],
            logo_alt=brand_doc["logo_alt"],
            customer=brand_doc.get("customer", ""),
            industry=brand_doc.get("industry", ""),
        )

        endpoint_registry = _build_endpoint_registry()
        # Keep the legacy attribute in sync so existing code/tests reading
        # settings.openai_endpoint_eastus2 keep working unchanged.
        if "secondary" in endpoint_registry:
            self.openai_endpoint_eastus2 = endpoint_registry["secondary"]

        agents: dict = {}
        for agent_key in AGENT_KEYS:
            agent_doc = document["agents"][agent_key]
            prefix = _agent_env_prefix(agent_key)
            context = f"agent '{agent_key}'"

            name = os.environ.get(f"{prefix}_NAME", "").strip() or agent_doc["name"]
            role = os.environ.get(f"{prefix}_ROLE", "").strip() or agent_doc["role"]
            deployment = os.environ.get(f"{prefix}_DEPLOYMENT", "").strip() or agent_doc["deployment"]

            endpoint_ref = os.environ.get(f"{prefix}_ENDPOINT", "").strip() or agent_doc.get(
                "endpoint_ref", ""
            )
            endpoint = _resolve_endpoint(endpoint_ref, endpoint_registry, context)

            temperature_raw = os.environ.get(f"{prefix}_TEMPERATURE", "").strip()
            if temperature_raw:
                try:
                    temperature = float(temperature_raw)
                except ValueError as exc:
                    raise ProfileError(
                        f"{context}: {prefix}_TEMPERATURE must be a number, got {temperature_raw!r}."
                    ) from exc
            else:
                temperature = float(agent_doc.get("temperature", 1.0))

            supports_temp_raw = os.environ.get(f"{prefix}_SUPPORTS_TEMPERATURE", "").strip()
            if supports_temp_raw:
                supports_temperature = _parse_bool(
                    supports_temp_raw, f"{context}: {prefix}_SUPPORTS_TEMPERATURE"
                )
            else:
                supports_temperature = bool(agent_doc.get("supports_temperature", False))

            api_version = (
                os.environ.get(f"{prefix}_API_VERSION", "").strip()
                or agent_doc.get("api_version", "").strip()
                or self.openai_api_version
            )

            max_completion_tokens_raw = os.environ.get(f"{prefix}_MAX_COMPLETION_TOKENS", "").strip()
            if max_completion_tokens_raw:
                max_completion_tokens = _parse_nonneg_int(
                    max_completion_tokens_raw, f"{context}: {prefix}_MAX_COMPLETION_TOKENS"
                )
            else:
                max_completion_tokens = int(agent_doc.get("max_completion_tokens", 0))

            max_context_chars_raw = os.environ.get(f"{prefix}_MAX_CONTEXT_CHARS", "").strip()
            if max_context_chars_raw:
                max_context_chars = _parse_nonneg_int(
                    max_context_chars_raw, f"{context}: {prefix}_MAX_CONTEXT_CHARS"
                )
            else:
                max_context_chars = int(agent_doc.get("max_context_chars", 0))

            response_instruction_raw = os.environ.get(f"{prefix}_RESPONSE_INSTRUCTION", "").strip()
            if response_instruction_raw:
                response_instruction = response_instruction_raw
            else:
                response_instruction = str(agent_doc.get("response_instruction", "")).strip()

            input_cost_raw = os.environ.get(f"{prefix}_INPUT_COST_PER_MILLION", "").strip()
            if input_cost_raw:
                input_cost_per_million = _parse_nonneg_float(
                    input_cost_raw, f"{context}: {prefix}_INPUT_COST_PER_MILLION"
                )
            else:
                input_cost_per_million = float(agent_doc.get("input_cost_per_million", 0.0))

            output_cost_raw = os.environ.get(f"{prefix}_OUTPUT_COST_PER_MILLION", "").strip()
            if output_cost_raw:
                output_cost_per_million = _parse_nonneg_float(
                    output_cost_raw, f"{context}: {prefix}_OUTPUT_COST_PER_MILLION"
                )
            else:
                output_cost_per_million = float(agent_doc.get("output_cost_per_million", 0.0))

            prompt_file_override = os.environ.get(f"{prefix}_PROMPT_FILE", "").strip()
            if prompt_file_override:
                prompt_path = Path(prompt_file_override)
                if not prompt_path.is_absolute():
                    prompt_path = REPO_ROOT / prompt_path
                if not prompt_path.is_file():
                    raise ProfileError(
                        f"{context}: {prefix}_PROMPT_FILE {prompt_file_override!r} not found "
                        f"at {prompt_path}."
                    )
                system_prompt = prompt_path.read_text(encoding="utf-8").strip()
                if not system_prompt:
                    raise ProfileError(
                        f"{context}: {prefix}_PROMPT_FILE {prompt_file_override!r} is empty."
                    )
            else:
                system_prompt = load_prompt(profile_dir, agent_doc["prompt_file"], context)

            agents[agent_key] = AgentConfig(
                key=agent_key,
                name=name,
                role=role,
                deployment=deployment,
                system_prompt=system_prompt,
                temperature=temperature,
                supports_temperature=supports_temperature,
                endpoint=endpoint,
                api_version=api_version,
                max_completion_tokens=max_completion_tokens,
                max_context_chars=max_context_chars,
                response_instruction=response_instruction,
                input_cost_per_million=input_cost_per_million,
                output_cost_per_million=output_cost_per_million,
            )

        self.agents = agents


settings = Settings()
