#!/usr/bin/env python3
"""Regenerate docs/AGENTS.md from app/agents/catalog.py.

    .venv/bin/python3 scripts/generate_agent_docs.py           # write
    .venv/bin/python3 scripts/generate_agent_docs.py --check   # exit 1 if stale

The doc is generated for the default ("power") profile; other profiles
change only display names, one-line roles and model deployments.
"""

import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

from app.agents.catalog import GUARDRAILS, build_agent_catalog  # noqa: E402
from app.agents.backend import FoundryConfig  # noqa: E402
from app.config import Settings  # noqa: E402

DOC_PATH = os.path.join(ROOT, "docs", "AGENTS.md")


def render() -> str:
    settings = Settings(profile_id="power")
    catalog = build_agent_catalog(settings.agents, backend="foundry", foundry_agent_prefix=FoundryConfig().agent_prefix)
    out = [
        "# Agent Squad — what each agent does and how",
        "",
        "<!-- GENERATED by scripts/generate_agent_docs.py from app/agents/catalog.py. Do not edit by hand. -->",
        "",
        "The runtime squad is one **Operations Coordinator** and five specialists. "
        "Display names, one-line roles and model deployments come from the active profile "
        "(`profiles/<id>/profile.json`; shown here for the default `power` profile). "
        "Everything else is derived from code, so it matches runtime behavior. "
        "The same data is served live at `GET /api/agents` and rendered on the in-app **Agent Squad** page.",
        "",
        "## How the squad works",
        "",
        "1. **Collect** — deterministic collectors (`app/operations/collectors/`) read Azure into cited findings. No AI involved.",
        "2. **Route** — `app/agents/routing.py` maps each finding category to its owning specialist and decides whether a debate is needed "
        "(cross-domain, high/critical, customer-impacting, or explicitly requested).",
        "3. **Analyze in parallel** — selected specialists reason over their evidence bundle and may call the read-only tools below.",
        "4. **Challenge** — in a debate, each specialist rebuts the others.",
        "5. **Synthesize** — the coordinator produces one recommendation; every claim must cite a finding ID and citations are validated.",
        "6. **Approve** — remediation becomes a reviewable proposal (Azure DevOps work item / PR, Terraform/CLI). Never auto-executed.",
        "",
        "Every response includes a `usage_summary` (tokens per round and per agent, model calls, cost) — see "
        "[FOUNDRY_ARCHITECTURE.md](FOUNDRY_ARCHITECTURE.md).",
        "",
        "## Guardrails (all agents)",
        "",
    ]
    out += [f"- {g}" for g in GUARDRAILS]
    out += ["", "## At a glance", "", "| Agent | Key | Handles | Model (power) |", "|---|---|---|---|"]
    for a in catalog:
        handles = ", ".join(h["label"] for h in a["handles"]) or "Synthesis of all specialists"
        out.append(f"| {a['icon']} **{a['name']}** | `{a['key']}` | {handles} | `{a['model_deployment']}` |")
    for a in catalog:
        out += ["", f"## {a['icon']} {a['name']} (`{a['key']}`)", "", f"**What:** {a['what']}", "", f"_{a['role']}_", ""]
        if a["handles"]:
            out.append("**Handles finding categories:** " + ", ".join(f"{h['label']} (`{h['category']}`)" for h in a["handles"]))
            out.append("")
        out.append("**How it works:**")
        out.append("")
        out += [f"{i}. {step}" for i, step in enumerate(a["how"], 1)]
        out += ["", "**Evidence it reads:** " + "; ".join(a["evidence_sources"]), ""]
        out.append("**Tools it can call (read-only, bounded):** " + ", ".join(f"`{t}`" for t in a["tools"]))
        out += ["", "**Produces:** " + "; ".join(a["outputs"]), ""]
        out.append(
            f"**Runs as:** Azure AI Foundry agent `{a['runtime']['foundry_agent']}` when `AGENT_BACKEND=foundry` "
            f"(name prefix set by `FOUNDRY_AGENT_PREFIX`), "
            f"otherwise a direct Azure OpenAI call. Model deployment `{a['model_deployment']}`; "
            f"overridable with `AGENT_{a['key'].upper()}_DEPLOYMENT`."
        )
    out += [
        "",
        "## Renaming or re-describing agents",
        "",
        "- **Display name / one-line role / model:** edit `profiles/<id>/profile.json` (no code change).",
        "- **Personality and instructions:** edit `profiles/<id>/prompts/<key>.txt`.",
        "- **What / how / outputs:** edit `AGENT_FUNCTIONS` in `app/agents/catalog.py`, then run "
        "`.venv/bin/python3 scripts/generate_agent_docs.py`.",
        "- **Which findings an agent owns:** `CATEGORY_AGENT_MAP` in `app/agents/routing.py`.",
        "- Agent **keys** (`cost_sentinel`, …) are stable identifiers used in env vars, Bicep overrides and Foundry agent names — do not rename them.",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    content = render()
    if "--check" in sys.argv:
        current = open(DOC_PATH, encoding="utf-8").read() if os.path.exists(DOC_PATH) else ""
        if current != content:
            print("docs/AGENTS.md is stale; run scripts/generate_agent_docs.py")
            return 1
        print("docs/AGENTS.md is up to date")
        return 0
    with open(DOC_PATH, "w", encoding="utf-8") as fh:
        fh.write(content)
    print(f"wrote {DOC_PATH}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
